name: Workflow Sync

on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/**"
  workflow_dispatch:
    
jobs:
  All_Repos_Common_Workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          
      - name: Running Workflow Sync
        env:
          REPOSITORIES: |
            JanssenProject/docker-jans-persistence-loader
          WORKFLOW_FILES: |
            .github/workflows/commit-check.yml
            .github/workflows/central_code_quality_check.yml
          GITHUB_TOKEN: ${{ secrets.MOWORKFLOWTOKEN }}
        run: |
          echo 
          wget https://raw.githubusercontent.com/mo-auto/scripts/main/org_workflows_sync.sh
          chmod u+x org_workflows_sync.sh
          bash org_workflows_sync.sh
