name: Workflow Sync

on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/**"
  workflow_dispatch:
    
jobs:
  All_Repos_Common_Workflows:
    runs-on: ubuntu-latest
    env:
      DRY_RUN: false
      PULL_REQUEST: true
      REPOSITORIES: |
        JanssenProject/docker-jans-persistence-loader
      WORKFLOW_FILES: |
        .github/workflows/commit-check.yml
        .github/workflows/central_code_quality_check.yml
      COMMIT_MESSAGE: 'ci(workflows): sync workflows'
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          
      - name: Running Workflow Sync
        uses: mo-auto/actions-sync-workflows@main
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.MOWORKFLOWTOKEN }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          PULL_REQUEST: ${{ env.PULL_REQUEST }}
